from .ashs_inference import HyperASHSInference
from .utils.huggingface import hf_disable_ssl_verification, hf_read_yaml, torch_hub_disable_ssl_verification
from .ashs_training import HyperASHSTraining
from .utils.tool import copy_or_link_file
from . import __version__
import argparse
import huggingface_hub as hf
import pandas as pd
import re
import pprint
import json
import textwrap
import os
import shutil
import yaml
import sys
from typing import Dict, Any, Tuple
from importlib.resources import files
import traceback
import tempfile
import io
from ssl import SSLCertVerificationError

def main():
    
    parser = argparse.ArgumentParser(
        prog='hrashs',
        description='HyperResASHS: High-Resolution Automatic Segmentation of Hippocampal Subfields',
        epilog="""HyperResASHS (C) 2026 by Yue Li, Paul Yushkevich, and UPenn Patch Lab.
                    Citation: https://doi.org/10.48550/arXiv.2508.17171
                    GitHub:   https://github.com/liyue3780/HyperResASHS.git""")
    
    # Create subparsers for different commands
    subparsers = parser.add_subparsers(dest='command', required=True, help='Available commands')
    
    # List atlases subcommand
    list_parser = subparsers.add_parser('list', help='List available HyperResASHS atlases')
    list_parser.add_argument('-l', '--long', action='store_true', help='Show detailed information about each atlas')
    
    # Describe atlas subcommand
    describe_parser = subparsers.add_parser('desc', help='Describe a specific HyperResASHS atlas')
    describe_parser.add_argument('atlas', type=str, help='Name of the atlas to describe or path to atlas config file')
    
    # Upload atlas subcommand
    upload_parser = subparsers.add_parser('upload', help='Upload a new HyperResASHS atlas to Hugging Face Hub')
    upload_parser.add_argument('atlas', type=str, 
                               help='Path to the atlas directory')
    upload_parser.add_argument('repo_id', type=str, 
                               help='Hugging Face Hub repository ID to upload the atlas to (e.g., username/repo_name)')
    upload_parser.add_argument('-n', '--no-add-to-directory', action='store_true',
                               help='Do not add the uploaded atlas to the active atlases directory on Hugging Face Hub')
    
    # Run segmentation subcommand
    run_parser = subparsers.add_parser('run', help='Run HyperResASHS segmentation pipeline')
    run_parser.add_argument('-a', '--atlas', type=str, required=True, 
                            help='Name of the atlas to use or path to atlas config file')
    run_parser.add_argument('-g', '--t1', type=str, required=True, 
                            help='Path to T1-weighted image')
    run_parser.add_argument('-f', '--t2', type=str, 
                            help='Path to T2-weighted image. Omit to run in T1-only ASHS mode.')
    run_parser.add_argument('-I', '--subject-id', type=str, default=None,
                            help='Subject ID for this experiment. If specified, outputs will be prefixed with the subject ID.')
    run_parser.add_argument('--reg-t1t2', type=str, default=None,
                            help='Provide the .mat file for the transform between the T1w and T2w image to use as '
                                 'the global T1w to T2w registration. The transform must be in the format used by ITK-SNAP, '
                                 'Greedy, and C3D and should be generated by performing registration with the T2w MRI '
		                         'as fixed image and the T1w MRI as moving.')
    run_parser.add_argument('--reg-t1t2-identity', action='store_true',
		                    help='Do not perform registration between T1w and T2w, trust image header instead')

    # Training command
    train_parser = subparsers.add_parser('train', help='Train a HyperResASHS model on a dataset')
    train_parser.add_argument('-c', '--config', type=str, required=True, 
                              help='Path to training configuration YAML file. See documentation for expected format.')
    train_parser.add_argument('-m', '--manifest', type=str, required=True, 
                              help='Path to manifest CSV file describing the training dataset. See documentation for expected format.')
    train_parser.add_argument('-l', '--labels', type=str, required=True, 
                              help='Path to ITK-SNAP label description file. See documentation for expected format.')
    train_parser.add_argument('-x', '--xval', type=str, default=None,
                              help='Cross-validation fold specification. See documentation for expected format.')
    train_parser.add_argument('-R', '--inr-random-seed', type=int, default=None, 
                              help='Specify random seed for the INR optimization; use to rerun failed INR experiments.')
    train_parser.add_argument('--inr-batch-size', type=int, default=None, 
                              help='Specify batch size for the INR optimization. Default: 2000')
    train_parser.add_argument('--inr-epochs', type=int, default=None, 
                              help='Number of epochs for the INR optimization. Default: 60')
    
    train_parser.add_argument('-s', '--stage', type=str, default='',
                              help='''
                              Run one or more selected stages of the training pipeline.
                              You can specify single stage as -s 1, or a range of stages as -s 1-3.
                              The stages are as follows:
                                1: Preprocessing (neck trim, registration, patch extraction)
                                2: INR training
                                3: nnU-Net preparation (resampling, cropping, and formatting for nnU-Net)
                                4: nnU-Net training        
                                5: Finalize                        
                              ''')
    train_parser.add_argument('-F', '--filter', type=str, metavar='REGEX' ,default=None,
                              help='''Restrict execution to image(s) that match specified regular expression. 
                              For stage 1 (preprocessing), REGEX will be matched to subject id and date.
                              For stage 2 (INR training), REGEX will be matched to subject id, date, and side.
                              For stage 3 (nnU-Net preparation), this is ignored.
                              For stage 4 (nnU-Net training), REGEX is matched to fold number (0-4)
                              ''')

    # List atlases subcommand
    check_parser = subparsers.add_parser('check', help='Check if HyperResASHS installed successfully')
    
    # Add common arguments for run and train subcommands
    for p in [run_parser, train_parser]:
        p.add_argument('-w', '--workdir', type=str, required=True, 
                       help='Path to working directory')
        p.add_argument('-N', '--no-overwrite', action='store_true', 
                       help='Do not overwrite existing results')
        p.add_argument('-t', '--threads', type=int, default=1, 
                       help='Number of parallel threads to use for segmentation [default: 1]')
        p.add_argument('--device', type=str, default='auto', 
                       help='''Device to use for segmentation (e.g. "cuda" or "cpu"). Default: auto-detect
                       To select specific GPU(s), use the CUDA_VISIBLE_DEVICES environment variable, e.g.:
                         CUDA_VISIBLE_DEVICES=0 hrashs run ...''')
        p.add_argument('-L', '--no-links', action='store_true', 
                       help='Do not create symlinks in the working directory; copy files instead. By default, symlinks are created to the input T1 and T2 images in the working directory')
        p.add_argument('-T', '--tidy', action='store_true',
                       help='Tidy mode. Reduce the number of intermediate files generated.')

    # Add -k flag for all relevant sub parsers
    for p in [list_parser, run_parser, describe_parser, train_parser, check_parser, upload_parser]:
        p.add_argument('-k', '--disable-ssl-verification', action='store_true', 
                       help='Disable SSL verification for Hugging Face Hub access')
        
    args = parser.parse_args()
    
    # Disable SSL verification if requested
    if args.disable_ssl_verification:
        hf_disable_ssl_verification()
        torch_hub_disable_ssl_verification()
    
    # Handle commands
    if args.command == 'list':
        list_atlases(args)
    elif args.command == 'desc':
        describe_atlas(args)
    elif args.command == 'run':
        run_segmentation(args)
    elif args.command == 'train':
        return run_training(args)
    elif args.command == 'check':
        return run_check(args)
    elif args.command == 'upload':
        return upload_atlas(args)
    else:
        raise ValueError(f"Unknown command: {args.command}")
        
    return 0

    
def get_atlas_listing(match=None):
    # Fetch upennpatchlab/hyperresashs_atlas_directory file active_atlases.yaml from HF:    
    # Read the list of available atlases from the Hugging Face Hub
    repo_list = hf_read_yaml(
        repo_id="upennpatchlab/hyperresashs_atlas_directory", 
        filename="active_atlases.yaml")        
    d = {}
    for repo in repo_list:
        repo_config = hf_read_yaml(repo_id=repo, filename=f"atlas.yaml")
        if match and not re.match(match, repo_config['metadata'].get('id',''), re.IGNORECASE):
            continue
        repo_config['metadata']['json'] = json.dumps(repo_config)
        repo_config['metadata']['repo'] = repo
        for k, v in repo_config['metadata'].items():
            if k not in d:
                d[k] = []
            d[k].append(v)
            
    df = pd.DataFrame(d)
    return df  
    
    
def print_atlas_listing(long=False, match=None):
    # Get the atlas listing as a DataFrame
    df = get_atlas_listing(match=match)
    df = df[[c for c in df.columns if c != 'json']]  # Exclude the json column from display
    df.columns = [c.capitalize().replace('_',' ') for c in df.columns]  
    
    # Print the atlas directory in a nice format
    if long:
        for _, row in df.iterrows():
            pprint.pp(row.to_dict())
    else:
        print(df[['Id','Name']].to_string(index=False)) 
        
        
def upload_atlas_to_hub(atlas_dir: str, repo_id: str, add_to_directory: bool = True):
    """Upload the atlas in specified folder to Hugging Face Hub."""
    try:
        hf.HfApi().upload_folder(folder_path=atlas_dir, repo_id=repo_id, repo_type='model')
        if add_to_directory:
            repo_list = hf_read_yaml(
                repo_id="upennpatchlab/hyperresashs_atlas_directory", 
                filename="active_atlases.yaml") 
            repos = set(repo_list)
            repos.add(repo_id)
            
            # Create a temporary file to hold the updated list of atlases
            buffer = io.BytesIO(yaml.dump(list(repos)).encode('utf-8'))
            hf.HfApi().upload_file(
                path_or_fileobj=buffer,
                path_in_repo="active_atlases.yaml",
                repo_id="upennpatchlab/hyperresashs_atlas_directory",
                repo_type='model')
                
    except Exception as e:
        print(f"Error uploading atlas to Hugging Face Hub: {e}")
        return

def list_atlases(args):
    """List available atlases."""
    try: 
        print_atlas_listing(long=args.long)
    except Exception as e:
        print(f"Error fetching atlas directory from Hugging Face Hub: {e}")
        return
    

def describe_atlas(args):
    """Describe a specific atlas."""
    # Read the list of available atlases from the Hugging Face Hub
    try: 
        print_atlas_listing(long=True, match=args.atlas)
    except Exception as e:
        print(f"Error fetching atlas directory from Hugging Face Hub: {e}")
        return
    
    
def upload_atlas(args):
    """Upload a new atlas to Hugging Face Hub."""
    upload_atlas_to_hub(args.atlas, args.repo_id, add_to_directory=not args.no_add_to_directory)
    
    
def print_header(metadata):

    main_citation = """\
        Li, Y., Khandelwal, P., Jena, R., Xie, L., Duong, M., Denning, A.E., Brown, C.A.,
        Wisse, L.E., Das, S.R., Wolk, D.A. and Yushkevich, P.A., 2025.
        Achieving detailed medial temporal lobe segmentation with upsampled
        isotropic training from implicit neural representation.
        arXiv preprint arXiv:2508.17171."""
    nnunet_citation = """\
        Isensee, F., Jaeger, P. F., Kohl, S. A., Petersen, J., & Maier-Hein, K. H. (2021). 
        nnU-Net: a self-configuring method for deep learning-based biomedical image segmentation. 
        Nature methods, 18(2), 203-211."""
    citations = [main_citation, nnunet_citation] + metadata.get('citations', [])

    print('' + '='*80)
    print(f"HyperResASHS {__version__} using atlas {metadata['id']} {metadata['version']}")
    print(f"     - {metadata['name']}")
    print()
    print(f"Please cite the following papers if you use this atlas in your research:")
    
    for i,ref in enumerate(citations):
        print(f"\n[{i+1}]  {textwrap.fill(textwrap.dedent(ref), width=74, subsequent_indent=' ' * 5)}")
    print('' + '='*80)
    
    
def warn_t1_only_mode():
    
    caution_citation = """\
        Wisse, L.E., Chételat, G., Daugherty, A.M., de Flores, R., la Joie, R., Mueller, S.G., 
        Stark, C.E., Wang, L., Yushkevich, P.A., Berron, D. and Raz, N., 2021. 
        Hippocampal subfield volumetry from structural isotropic 1 mm3 MRI scans: A note of caution. 
        Human brain mapping, 42(2), pp.539-550."""
    
    print('\n' + '*'*80)
    print("WARNING: Running in T1-only ASHS mode. ")
    print("T1-only ASHS mode is only recommended for atlases that do not label hippocampal subfields!")
    print("\nFor more information, see:")
    print(f"    {textwrap.fill(textwrap.dedent(caution_citation), width=74, subsequent_indent=' ' * 5)}")
    print('' + '*'*80 + '\n')
    
class Logger(object):
    
    class Stream(object):
        def __init__(self, original_stream, log_file):
            self.original_stream = original_stream
            self.log_file = log_file

        def write(self, message):
            self.original_stream.write(message) # Write to console
            self.log_file.write(message)      # Write to file

        def flush(self):
            # This flush method is important for proper buffering behavior
            self.original_stream.flush()
            self.log_file.flush()
    
    def __init__(self, filename):
        self.log_file = open(filename, "w")
        self.out = self.Stream(sys.stdout, self.log_file)
        self.err = self.Stream(sys.stderr, self.log_file)
        sys.stdout = self.out # Redirect all print statements to this object
        sys.stderr = self.err # Redirect all error messages to this object
        
    def close(self):
        self.log_file.close()
        sys.stdout = self.out.original_stream # Restore original stdout
        sys.stderr = self.err.original_stream # Restore original stderr
        
    def __del__(self):
        self.close()
        
        
def _fetch_template(atlas_config : Dict[str,Any]) -> str:
    # Fetch the template from Hugging Face Hub if specified in the atlas config
    template_hf = atlas_config.get('template', {}).get('hf', None)
    if template_hf:
        template_path = hf.snapshot_download(template_hf)
    else:
        template_path = atlas_config.get('template', {}).get('local', None)
        if template_path is None:
            raise ValueError("No template specified in atlas configuration. Please check the atlas configuration and try again.")
        
    return template_path


def write_config_files(atlas_config : Dict[str,Any], atlas_local_path:str, work_dir: str, num_threads: int, training:bool=False):
    
    # Set up the atlas configuration the way Yue's code expects it
    config_src = atlas_config['config']
    config_src['TEST_PATH'] = work_dir
    config_src['TEMPLATE_PATH'] = os.path.join(_fetch_template(atlas_config), 'hyperashs-template')
    config_src['ATLAS_PATH'] = atlas_local_path
    config_src['ITKSNAP_LABEL_FILE'] = os.path.join(atlas_local_path, 'itksnap_labels.txt')
    config_src['GREEDY_NUM_THREADS'] = num_threads
    config_src['NNUNET_NUM_THREADS'] = num_threads
    config_src['FILE_NAME_CONFIG'] = os.path.join(work_dir, 'config', 'ashs_filename_scheme.yaml')
    
    # Add sides to the config for training if not already present
    config_src['SIDES'] = config_src.get('SIDES', ['left', 'right'])
    
    # Write the config to the working directory
    os.makedirs(os.path.join(work_dir, 'config'), exist_ok=True)
    fn_config_yaml = os.path.join(work_dir, 'config', f'configtest_{config_src["EXP_NUM"]}_{config_src["MODEL_NAME"]}.yaml')
    with open(fn_config_yaml, 'wt') as f:
        yaml.dump(config_src, f)
        
    # Write the preferred naming scheme to the working directory
    fn_scheme = files('hyperresashs').joinpath('config_templates/ashs_filename_scheme.yaml')
    with fn_scheme.open('r') as f:
        _ashs_naming_scheme = f.read()
    with open(config_src['FILE_NAME_CONFIG'], 'wt') as f:
        f.write(_ashs_naming_scheme)
    
    # Create the config in the way that Yue's code expects it
    config = yaml.safe_load(open(fn_config_yaml, 'r'))
    
    return config


def run_check(args):
    """Check if HyperResASHS installed successfully."""
    
    # Check if we can connect to Hugging Face Hub
    try:
        get_atlas_listing()
        print("Successfully connected to Hugging Face Hub.")
    except Exception as e:
        print("SSL certificate verification failed when trying to connect to Hugging Face Hub.")
        print("This may be due to an issue with your internet connection, firewall, or SSL configuration.")
        print("If you are behind a corporate firewall, you may need to configure your system to trust the appropriate certificates.")
        print("Please check your internet connection and SSL settings, and try again.")
        print("** To disable SSL verification (not recommended), you can use the -k flag with hrashs commands. **")
        return 1
    
    # Test nnU-Net
    try:
        # Create a temp directory for nnUnet paths
        with tempfile.TemporaryDirectory() as temp_dir:
            for k in ['raw', 'preprocessed', 'results']:
                os.makedirs(os.path.join(temp_dir, k), exist_ok=True)
                os.environ[f'nnUNet_{k}'] = os.path.join(temp_dir, k)
            
        from nnunetv2.inference.predict_from_raw_data import nnUNetPredictor
        print("Successfully imported nnU-Net predictor. nnU-Net is accessible.")
    except ImportError as e:
        # Print original error and stack trace for debugging
        print("Error: HyperResASHS cannot access its internal modified nnU-Net package.")
        print("Original error message:")
        traceback.print_exc() 
        print("System path:")
        for p in sys.path:
            print(f"  {p}")
        return 1
    
    # Test INR code
    try:
        from .submodules.multi_contrast_inr.main import main as inr_main
        print("Successfully imported multi-contrast INR code. INR code is accessible.")
    except ImportError as e:
        print("Error: HyperResASHS cannot access its internal multi-contrast INR code.")
        print("Original error message:")
        traceback.print_exc() 
        print("System path:")
        for p in sys.path:
            print(f"  {p}")
        return 1
    
    # Test for Torch/CUDA
    try:
        import torch 
        print("Successfully imported PyTorch. PyTorch is accessible.")
        print(f"  Torch installed:  {hasattr(torch, '__version__')}")
        if hasattr(torch, '__version__'):
            print(f"  Torch version:    {torch.__version__}")
            cuda_available = torch.cuda.is_available()
            print(f"  CUDA available:   {cuda_available}")
            if cuda_available:
                print(f"  CUDA version:     {torch.version.cuda}")
                print(f"  Device name:      {torch.cuda.get_device_name(0)}")
        else:
            print("  Warning: Could not determine PyTorch version. This may indicate an issue with the PyTorch installation.")
    except ImportError as e:
        print("Error: PyTorch is not installed or cannot be accessed.")
        print("Original error message:")
        traceback.print_exc() 
        return 1
    
    print("HyperResASHS installation check successful!")
    print(f"Version: {__version__}")
    return 0


def get_atlas(atlas:str) -> Tuple[str, str]:

    # First, the atlas may be either a local path to the atlas or a huggingface hub id.
    atlas_local_path = None
    if os.path.isdir(atlas) and os.path.exists(atlas):
        # If it's a local path, we assume it's a config file and we load the config directly from it
        with open(os.path.join(atlas, 'atlas.yaml'), 'r') as f:
            atlas_config = yaml.safe_load(f)
            atlas_local_path = atlas

        # Print the header with atlas information and citations
        print_header(atlas_config['metadata'])
    else:
        # Fetch the atlas the user wants
        df_meta = get_atlas_listing(match=atlas)
        if len(df_meta) == 0:
            raise ValueError(f"Error: No atlases found matching '{atlas}'. Please check the atlas name and try again.")
        elif len(df_meta) > 1:
            raise ValueError(f"Error: Multiple atlases found matching '{atlas}'. Please be more specific.")
            
        # Read the atlas configuration from the JSON metadata
        atlas_config = json.loads(df_meta.iloc[0]['json'])
        
        # Print the header with atlas information and citations
        print_header(atlas_config['metadata'])
        
        # Download the enture atlas snapshot
        atlas_local_path = hf.snapshot_download(df_meta.iloc[0]['repo'])    
        
    return atlas_config, atlas_local_path
        

def run_segmentation(args):
    """Run the segmentation pipeline."""
    
    # Create a logger
    os.makedirs(os.path.join(args.workdir, 'logs'), exist_ok=True)
    logger = Logger(os.path.join(os.path.join(args.workdir, 'logs'), 'hyperashs_log.txt'))
    
    # Load the atlas from Hugging Face Hub or local path
    atlas_config, atlas_local_path = get_atlas(args.atlas)
        
    # If no T2 image is provided, print a warning about T1-only ASHS mode
    if args.t2 is None:
        warn_t1_only_mode()
                    
    # Set up the atlas configuration the way Yue's code expects it
    config = write_config_files(atlas_config=atlas_config, atlas_local_path=atlas_local_path, 
                                work_dir=args.workdir, num_threads=args.threads, training=False)

    # Create the inferencer
    tester = HyperASHSInference(config, cleanup_config=atlas_config.get('cleanup', None))
    
    # Create links in the working directory
    create_links, overwrite_existing = not args.no_links, not args.no_overwrite
    
    # Initial registration
    reg_t1t2_mat = 'identity' if args.reg_t1t2_identity else args.reg_t1t2
            
    # Run the segmentation 
    print('-' * 60)   
    print(f"Running HyperResASHS with:")
    print(f"  Atlas:   {args.atlas}")
    print(f"  T1:      {args.t1}")
    print(f"  T2:      {args.t2 or 'None (T1-ASHS mode)'}")
    print(f"  Workdir: {args.workdir}")
    if args.subject_id:
        print(f"  Subject: {args.subject_id}")
    print('-' * 60)
    tester.run_inference_for_one_case(mprage=args.t1, tse=args.t2, case_path=args.workdir, 
                                      save_intermediates=args.tidy is False, 
                                      overwrite_existing=overwrite_existing, 
                                      create_links=create_links,
                                      device=args.device, 
                                      subject=args.subject_id,
                                      reg_t1t2_mat=reg_t1t2_mat)


def run_training(args) -> int:
    """Run the training pipeline."""
    
    create_links, overwrite_existing = not args.no_links, not args.no_overwrite

    # Create a logger
    os.makedirs(os.path.join(args.workdir, 'logs'), exist_ok=True)
    logger = Logger(os.path.join(os.path.join(args.workdir, 'logs'), 'hyperashs_log.txt'))
    
    # Load the training configuration from the specified YAML file
    try:
        with open(os.path.join(args.config), 'r') as f:
            atlas_config = yaml.safe_load(f)

        # Print the header with atlas information and citations
        print_header(atlas_config['metadata'])

    except Exception as e:
        print(f"Error loading atlas configuration: {e}")
        return -1
    
    # Set up the atlas configuration the way Yue's code expects it
    config = write_config_files(atlas_config=atlas_config, atlas_local_path=args.workdir, 
                                work_dir=args.workdir, num_threads=args.threads, training=True)
    
    # Process the stage argument to determine which stages to run
    stage_no = set()
    if args.stage:
        for part in args.stage.split(','):
            if '-' in part:
                start, end = map(int, part.split('-'))
                stage_no.update(range(start, end + 1))
            else:
                stage_no.add(int(part))
    else:
        stage_no = {1, 2, 3, 4, 5}  # Default to running all stages if not specified

    # Create the training object
    trainer = HyperASHSTraining(config, 
                                manifest_file=args.manifest,
                                label_file=args.labels,
                                xval_file=args.xval,
                                output_dir=args.workdir,
                                overwrite_existing=overwrite_existing,
                                save_intermediates=args.tidy is False, 
                                create_links=create_links)
    
    # Set up stages and validations for the training pipeline
    stages = [
        (1, trainer.preprocess, {'filter': args.filter}, None),
        (2, trainer.train_inr, {'filter': args.filter, 'device': args.device, 
                                'random_seed': args.inr_random_seed, 
                                'batch_size': args.inr_batch_size, 
                                'num_epochs': args.inr_epochs}, trainer.validity_check_inr_results),
        (3, trainer.prepare_nnunet, {}, None),
        (4, trainer.train_nnunet, {'filter': args.filter, 'device': args.device}, trainer.validity_check_nnunet_results),
        (5, trainer.finalize, {'full_metadata': atlas_config}, None)
    ]

    # Run the specified stages    
    for i_stage, stage_func, stage_kwargs, validity_check in stages:
        if i_stage in stage_no:
            # Run the stage
            stage_func(**stage_kwargs)
            if max(stage_no) == i_stage:
                return 0
            
        # Perform validity check at the end of this stage. This prevents moving on
        # to the next stage if there were failures in the current stage. 
        if validity_check is not None:
            if validity_check() is False:
                return 1
  
    return 0