# global configure
EXP_NUM: 292
MODEL_NAME: 'IsotropiSeg'
TRAINER: 'ModAugUNetTrainer'
CONDITION: 'in_vivo'
UPSAMPLING_METHOD: "INRUpsampling"

# test 
TEST_PATH: '/home/user/data/Data/seg_project/test_exp2/test_data3'

# trim neck shell script path
NECK_SHELL: 'shell/trim_neck.sh'  # this is the shell script to trim the neck for 3T-T1w image
TEMPLATE_PATH: '/your/path/for/ASHS/template'  # it can be downloaded from the ASHS atlas
