# global configure
EXP_NUM: 0000
MODEL_NAME: ''
TRAINER: ''
CONDITION: 'in_vivo'
UPSAMPLING_METHOD: ""

# test 
TEST_PATH: ''
TEMPLATE_PATH: ''

# model download
HF_MODEL_REPO: ''  # optional: (e.g., "username/Dataset292_IsotropicSeg")

# file names config
FILE_NAME_CONFIG: ''
