# global configure
EXP_NUM: 292
MODEL_NAME: 'IsotropicSeg'
TRAINER: 'ModAugUNetTrainer'
CONDITION: 'in_vivo'
UPSAMPLING_METHOD: "INRUpsampling"

# test 
TEST_PATH: '/home/liyue7/data/Data/D17_T1T2_ASHS/test_exp_temp/test_data'
TEMPLATE_PATH: '/home/liyue7/data/Data/D14_3T_Mix_7T/Clinical_Exp/Rerun/template'

# model download
HF_MODEL_REPO: 'liyue3780/Dataset292_IsotropicSeg'  # replace YOUR_USERNAME with your actual Hugging Face username
