# global configure
EXP_NUM: 0000
MODEL_NAME: ''
TRAINER: ''
CONDITION: 'in_vivo'
UPSAMPLING_METHOD: ""

# test 
TEST_PATH: ''

# trim neck shell script path
NECK_SHELL: ''  # this is the shell script to trim the neck for 3T-T1w image
TEMPLATE_PATH: ''  # it can be downloaded from the ASHS atlas
